---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxcd-test-repo
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/sahilkeshri1704/fluxcd-test-repo.git
